name: Deploy Website to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm install
    - run: npm run build
      env:
        CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
        CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://genres.sydneymusic.net --delete --exclude ".git/*" --exclude "node_modules/*"

    - name: Invalidate Cloudfront Cache
      run: aws cloudfront create-invalidation --distribution-id EI0LHD238ZRJP --paths "/*"